### ISSUE TITLE
Attribute matching

### ISSUE THREAD

**Issue by jamaa** [bluemodel/BlueM.QGISInterface#6]
Two suggestions concerning user experience for attribute matching:

- [x] allow the user to edit already entered manual attribute matches. Currently, any already entered matches are lost when you click on the "manually" button again, I don't see a way to edit already entered information.
- [ ] remember attribute matches. Currently, any entered attribute matches are lost when you close and reopen the plugin window. Remembering attribute matches across QGIS sessions would of course be even better, but I guess would require some kind of settings file (linked to the QGIS project) to be generated and stored somewhere. I have seen this done e.g. by the [Qgis2threejs plugin](https://github.com/minorua/Qgis2threejs)

**Comment by MartinGrosshaus** [comment]
I've got a solution for your first suggestion.
It's a new function that gets triggered every time the selection window is opened.
This function checks if a matching-dictionary already exists for this file type - if it does, the previous matches are automatically selected in the combo boxes.
This even works if the plugin was temporarily closed or the selected layer was swapped :-)
-> im gonna put it into the code - thanks for the suggestion!

Regarding suggestion 2:
As you anticipated, to make it work between QGIS sessions would require a settings file - which is a bit nasty.
I once thought about such a settings file for the checkboxes in the settings tab, but it's quite a piece of work.
In this special case a little cost-benefit-analysis still says that it's too complicated for the fringe scenario of a user who wants to slightly edit his old matches in a new QGIS session. 
Saving the old matches is not the only issue: It would also be necessary to identify the layer for which the matches were saved or their would need to be the option to select between different saves etc...
I think it's better in such a case to "push" the user towards using the standardized attribute names to provide a swift matching :-)

**Comment by jamaa** [comment]
great! I bumped the version number to 1.2 and updated the changelog in 3571d50d20a2b7f455b40f61ebe720ed2ea4925c
